export const orderNumber = state => state.order.number;
export const burgerConstructorData = state => state.burgerConstructor.data;
export const burgerIngredientsData = state => state.burgerIngredients.data;
export const ingredientOpenIngredient = state => state.ingredientOpen.ingredient;
export const orderInfoData = state => state.orderInfo.data;
export const orderInfoTotal = state => state.orderInfo.total;
export const orderInfoTotalToday = state => state.orderInfo.totalToday;
export const userInfoUser = state => state.userInfo.user;
export const userInfoCanResetPassword = state => state.userInfo.canResetPassword;